configuration.lua.sample
main.lua

When I read I often reach for the built-in dictionary feature but the built-in dictionaries sometimes do not have the word I am looking for.
I thought it would be convenient to have the option to make the Dictionary (AI) button appear on that dictionary screen (much like how the `Add to Vocabulary Builder` button can appear). I gated it behind a configuration parameter. This way I can invoke the AI dictionary when the built in dictionary sucks.
1. Add a field to `features` called `show_dictionary_button_in_dictionary_popup` which when enabled makes the "Dictionary (AI) button appear in the normal dictionary view
2. Add the `onDictButtonsReady` method to the `Assistant` widget so that it adds the `Dictionary(AI)` button to the screen.
1. I loaded it up on my Kobo with the …

Add ability to open AI dictionary entry from normal dict view

---

README.md
api_handlers/ollama.lua
configuration.lua.sample
gpt_query.lua

This PR adds support for using Ollama with the plugin. Ollama provides an convenient way to run AI models locally to test a varied range of models and minimize costs.
- Added `OllamaHandler` and loaded it with `loadHandler` in `provider_handlers`.
- Added checks in `OllamaHandler` for `base_url` and `model` along with `api_key` as all of these are required and cannot have defaults.
- Updated `configuration.lua.sample` to have sample configuration for Ollama and added mentions of Ollama in `README.md` wherever applicable.
- Successfully tested with multiple locally-hosted Ollama models.
- Verified compatibility with existing assistant features.
- Ensured no changes for users not using Ollama.

Add Ollama support

---

README.md
configuration.lua.sample
main.lua
recapdialog.lua

Adds an optional prompt for books on open to give the user an AI generated recap of the book so far to help them pick up where they left off. Only prompts for books that have already been opened but not read in 28 hours and are less than 95% complete. Updates main, configuration, and ReadMe in kind.
Open to prompt, message string, time since open cutoff, and percent_finished cutoff tweaks (or whatever else). Can also add the time cutoff to config. Can also add a percent_finished cutoff for the start, if the book is less than 5% for example.

Adds Recap Dialog as a Built-in Prompt

---

api_handlers/deepseek.lua

This is just so it's easier to tell why the API calls are failing. For example, it can be due to lack of funds.

DeepSeek: If there's more information about the API error, show it in the message

---

api_handlers/groq.lua
configuration.lua.sample
gpt_query.lua

groq platform provides really **fast** hardware for LLM models, it would be quite good experiance when using in KOReader as it's without streaming display.
like Mistral API, the `is_context` attr needs to be removed.

add groq support

---

chatgptviewer.lua
configuration.lua.sample
dialogs.lua

Current behavior would be unchanged -- displays raw plaintext from the configured LLM
Setting `render_markdown = true` treats the LLM response as markdown. The internal `apps/filemanager/lib/md` is used to convert markdown -> HTML, and the HTML is rendered in a `ScrollHtmlWidget` instead of `ScrollTextWidget`.

add option for markdown -> HTML conversion and rendering

---

api_handlers/gemini.lua
configuration.lua.sample

Gemini 2.5 models enable thinking by default. This results in several seconds of extra latency before a response appears. For simple explain or translate prompts, thinking is likely overkill.
This PR allows setting `generationConfig.thinkingConfig.thinkingBudget` in the request to Gemini. By default this is `nil` (unset) and will use Google's defaults. Setting to `0` disables thinking. Other values are probably less useful, but might as well be configurable.
https://ai.google.dev/gemini-api/docs/thinking
> Note: Thinking is enabled by default for the 2.5 series models. Read the section on [setting a thinking budget](https://ai.google.dev/gemini-api/docs/thinking#set-budget) for details and configuration.

expose thinkingBudget option for gemini

---

chatgptviewer.lua
configuration.lua.sample
dialogs.lua

1. add `markdown_font_size` in the configuration file, define a normal text size for the markdown result.
2. the new added option is optional, if user use an old configuration without the option, script uses a default value without crashing.
3. refactor the`createAndShowViewer` function, removed  `render_markdown`  argument,  without reading `CONFIGURATION.features.render_markdown` in many places.
4. optimize the output response for better markdown compatible format. now `⮞ Assistant:`  `⮞ User` will show in a `h3` heading line.

Add markdown_font_size option

---

dialogs.lua

There's a bug in the `Ask Another Question` button, where user clicks predefined prompt, the followed up prompt didn't replace keywords `{title}` / `{author}` / `{highlight}`, then sending a contentless prompt to model.
This PR refactor the prompt formating logic, use the same function `formatUserPrompt` in both first time asking and follow up asking.

fix: ask another question buttons knows nothing about user reading texts

---

README.md
configuration.lua.sample
dialogs.lua
dictdialog.lua
main.lua
recapdialog.lua

This PR allows the Ask and Recap options to be triggered by custom shortcuts. This enables the user to ask anything about the book without needing to highlight text first. It also enables triggering the recap at any time.
I also changed the recap prompt to be configurable, with a fallback to the previous prompt.

Standalone Ask and Recap shortcuts

---

chatgptviewer.lua
dialogs.lua
dictdialog.lua
gpt_query.lua
main.lua
recapdialog.lua
update_checker.lua

The `Recap` / `Dictionary` and `Updater` modules didn't show any message while doing networking, the screen freezes for quite a while if network/model is slow.
This PR adds a loading dialog (just like other functions) while query model. Networking actions put in async procs (`UIManager:show(...)` and then `UIManager:scheduleIn(...)` )
also, adds an icon to all info message dialogs.
and some code clean up in `main.lua`, move common widget to the top line. use `logger.warn` instead of `print()` on errors.

Adding loading message in recap / dict / updater

---

README.md

adds a tip about long-tap on a single word for the highlight popup, otherwise a dictionary dialog pops.

add: long-tap tips

---

dialogs.lua
dictdialog.lua
gpt_query.lua
recapdialog.lua

Fix error handling during the calling of AI services.
the return value of `queryChatGPT()` havn't properly processed, if error occured, user only face an empty result, or a crash :(
Now the error is detected and shown in a `InfoMessage`. also logged into `crash.log`.

fix AI service error handling

---

chatgptviewer.lua

- use Noto Sans font as default, it looks considerably better on e-ink
- use line-height 1.3 which makes it more similar to textbox, and looks good with noto sans
- set text-alight justify to match text box
mostly based on dictquicklookup defaults

fix: update html view css to match text view better

---

dialogs.lua
dictdialog.lua
gpt_query.lua
main.lua
recapdialog.lua

- Separate the custom prompt process function.
- Rename some variables to clarify the working process.
- Simplify error handling in `Querier:load_model`.

Refactor main dialog

---

chatgptviewer.lua
dialogs.lua
dictdialog.lua
main.lua
recapdialog.lua

Now user can switch to different model without editing the configuration.lua file.
the dialog can be accessed in 2 methods:
- Top Menu(book opened) -> TOOLS -> Page 2 `More tools` -> `Assitant Provider Switch`
- A second botton next to "Ask another question" on a response view.
**screenshot**

adds AI Provider switch dialog

---

README.md
configuration.lua.sample
gpt_query.lua
main.lua

- use `visible = false` to hide a provider profile, (following the same logic with `show_on_main_popup = false` in prompt config)
- adds `default = true` to help selecting a provider if the `provider =` is not defined (if multiple default is defined, the result will be  a random one)

Profile visible settings discussed in #50

---

README.md
configuration.sample.lua

- fix a syntax error in the example configuration
- renname example file to `configuration.sample.lua` to allow regular syntax check
- updated doc

fix configuration sample; rename to configuration.sample.lua

---

chatgptviewer.lua
configuration.sample.lua
dialogs.lua
main.lua

Mostly a code refactor PR, not much feature changes.
1. rewrite `ChatGPTDialog` to `AssistantDialog` class, simplifing function calls, without passing around references.
2. clearify some function names, funcion with prefix `_` means module internal use.
3. pass a callback func `onShowSwitchModel` instead of the whole `assitant` main object to the viewer.
4. avoid user inputs an empty question.
5. when `Ask Another Question`  and clicks a button, shows `> User: Translate` as user content line instead of the very long custom defined prompt.

refactor ChatGPTDialog to AssistantDialog as OOP 

---

dialogs.lua

adds a config button ( the gear ) to the left of main dialog titlebar.
it's handful when the model service is unavailable and to switch to another.

add: modle switch button on the left of main input dialog titlebar

---

chatgptviewer.lua

when using "ask another question", the result are concated, but the scroll position was not right.
- use the last time total pages count to calculate the scroll position.
- the scrollbar seems buggy, but that's a koreader offcial widget, maybe try to fix it to upstream.

fix: improve scrolling behavior in ChatGPTViewer update function

---

configuration.sample.lua

- update default gemini model to 2.5-flash, which has a free tier so best suitable as the default.
- update model list url
- set max_tokens to 1M to reflect the new model's spec
- set thinking_budget to 0

update gemini default settings

---

chatgptviewer.lua
dictdialog.lua
recapdialog.lua

- SwitchModel button was not working in recap and dict dialog, for the callback was not defined.
- remove `ChatGPTViewer.showAskQuestion` flag variable, instead, only show the button when the callback is defined. same rule goes to `ChatGPTViewer:onShowSwitchModel`.

fix SwitchModel button in recap and dict dialog

---

prompts.lua

AI suggested that 
The use of goto is idiomatic in Lua for creating a continue statement, but it can sometimes be less readable for developers unfamiliar with this pattern. You can achieve the same logic with a standard if block, which might improve clarity.

rewrite and remove goto statement to improve clarity

---

.gitignore
chatgptviewer.lua
mdparser.lua

Introduce a full featured markdown parser, hoedown. We can see table results from the AI response.
But hoedown is C written, and compiled to shared object, makes this feature platform dependence.
All linux-based native KOReader's (kindle, kobo, remarkable, tolino ...) should be easily enable this feature, only some [extra steps](https://github.com/boypt/hoedown4eink?tab=readme-ov-file#install) needed.  Android platform is not available now, until the KOReader includes hoedown in the App.
I believe this feature is not necessary for normal users (AI not always generate complicated results containing tables). It will use the buildin pure LUA parser as before. **This feature is like a plugin to the plugin.**
Also minor changed to the viewer CSS:
- default text no longer justify, just show the …

Full featured markdown parser

---

README.md
configuration.sample.lua
dialogs.lua
dictdialog.lua
main.lua
prompts.lua

Introcduce hold action to the prompt buttons in the Assitant dialog. A confirm box shows a prompt function descrition and ask whether to add or remove the button from the main popup.
this feature depreciate the `show_on_main_popup = true` switch in the configuration file (stills works, but the user action config has priority.). also depreciate the `show_dictionary_button_in_main_popup` switch.
make the `dictionary_translate_to` optional, will use `response_language` by default.

Hold buttons to add/remove from main popup

---

configuration.sample.lua
dialogs.lua
dictdialog.lua
gpt_query.lua
main.lua
recapdialog.lua
settingsdialog.lua

- `response_language` in the configuration is now optional, it would be more friendly to just use the UI language to respond
- user prefers other wise can also set the `response_language`
- `forced_stream_mode` defaults to true
- `ai_translate_override` defaults to false
- stream dialog size adjust

AI response follow UI language as default

---

api_handlers/base.lua
chatgptviewer.lua
configuration.sample.lua
dialogs.lua
dictdialog.lua
gpt_query.lua
recapdialog.lua
settingsdialog.lua

- Adds a menu popup on the left top conner of settings dialog
- adjust response font size and language
- deprecated configs: `response_language` , `dictionary_translate_to`, `markdown_font_size`

Add setting menu for language and font size

---

assistant_settings.lua
assistant_viewer.lua
main.lua

Some adjust to the "Export Conversations to File" featue.
KOReader has an unnoticiable feature: notebook ( top right button menu-> Book Info -> 2nd Page -> NoteBook file), which can be used to store AI conversations. By using the `BookInfo` module we can CRUD on the AI conversation easily.
- the default location of notebook file is a `.txt` along side with the ebook file
- can be changed location in BookInfo model
- Edit / View the txt file from the menu

feat: notebook file as conversation logs
